# Generated by Django 6.0 on 2026-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_department_department_id_hod_hod_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Annual CTC (Cost to Company) in INR', max_digits=10),
        ),
    ]
