"""
Django settings for the HRMS project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see:
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
import environ
from hrms.config.django import DJANGO_APPS, DJANGO_DEFAULT_MIDDLEWARE, DJANGO_CORE_TEMPLATES, DJANGO_AUTH_PASSWORD_VALIDATORS
from hrms.config.drf import DRF_REST_FRAMEWORK
from hrms.config.third_party import THIRD_PARTY_APPS, SPECTACULAR_CONFIG
from hrms.config.django import LOCAL_APPS
from hrms.config.utils import get_db_config, get_simple_jwt_config

# ==============================================================================
# 1. CORE CONFIGURATION
# ==============================================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    # Set default values and casting types
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    CORS_ALLOWED_ORIGINS=(list, [])
)

# Read the .env file
# Points to the directory containing the .env file (adjusted relative to settings.py)
env_file_path = os.path.join(BASE_DIR.parent, 'env/hrms_env/.env')
environ.Env.read_env(env_file_path)



# ==============================================================================
# 2. SECURITY SETTINGS
# ==============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# In production, this should be a comma-separated list of domains in your .env
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# ==============================================================================
# 3. INSTALLED APPS
# ==============================================================================


THIRD_PARTY_APPS = THIRD_PARTY_APPS

LOCAL_APPS = LOCAL_APPS

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


# ==============================================================================
# 4. MIDDLEWARE
# ==============================================================================

MIDDLEWARE = DJANGO_DEFAULT_MIDDLEWARE + ['apps.audit.middleware.AuditMiddleware']

ROOT_URLCONF = 'hrms.urls'

TEMPLATES = DJANGO_CORE_TEMPLATES

WSGI_APPLICATION = 'hrms.wsgi.application'


# ==============================================================================
# 5. DATABASE
# ==============================================================================
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = get_db_config(env)

# Custom User Model
AUTH_USER_MODEL = env('AUTH_USER_MODEL')


# ==============================================================================
# 6. PASSWORD VALIDATION
# ==============================================================================
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = DJANGO_AUTH_PASSWORD_VALIDATORS


# ==============================================================================
# 7. INTERNATIONALIZATION
# ==============================================================================
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==============================================================================
# 8. STATIC & MEDIA FILES
# ==============================================================================
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# In production, run 'python manage.py collectstatic' to move files here
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# URL used to access media (e.g., http://localhost:8000/media/face.jpg)
MEDIA_URL = '/media/'

# Path where uploaded files are stored on the disk
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ==============================================================================
# 9. API CONFIGURATION (DRF & JWT)
# ==============================================================================

REST_FRAMEWORK = DRF_REST_FRAMEWORK

SIMPLE_JWT = get_simple_jwt_config(env)

SPECTACULAR_SETTINGS = SPECTACULAR_CONFIG


# ==============================================================================
# 10. CORS CONFIGURATION
# ==============================================================================

# If True, allows any website to call your API (Development only)
CORS_ALLOW_ALL_ORIGINS = DEBUG

# In production, set CORS_ALLOW_ALL_ORIGINS = False and use the list below
if not DEBUG:
    CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')


# ==============================================================================
# 11. GEMINI API CONFIGURATION (for OCR feature)
# ==============================================================================

GEMINI_API_KEY = env('GEMINI_API_KEY', default='')
