"""
Django settings for the HRMS project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see:
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
import environ

# ==============================================================================
# 1. CORE CONFIGURATION
# ==============================================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    # Set default values and casting types
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    CORS_ALLOWED_ORIGINS=(list, [])
)

# Read the .env file
# Points to the directory containing the .env file (adjusted relative to settings.py)
env_file_path = os.path.join(BASE_DIR.parent, 'env/hrms_env/.env')
environ.Env.read_env(env_file_path)

# Add 'apps' directory to sys.path
# This allows clean imports like 'from users.models import...' instead of 'apps.users...'
APPS_DIR = BASE_DIR / 'apps'
sys.path.insert(0, str(APPS_DIR))


# ==============================================================================
# 2. SECURITY SETTINGS
# ==============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# In production, this should be a comma-separated list of domains in your .env
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# ==============================================================================
# 3. INSTALLED APPS
# ==============================================================================

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',              # The API Toolkit
    'rest_framework_simplejwt',    # For Auth Tokens
    'corsheaders',                 # To allow Frontend access
    'django_filters',              # Advanced filtering
    'drf_spectacular',             # For API Schema and Docs
]

LOCAL_APPS = [
    'users.apps.UsersConfig',            # Custom user app
    'audit.apps.AuditConfig',            # Audit logs app
    'leaves.apps.LeavesConfig',
    'organization.apps.OrganizationConfig',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


# ==============================================================================
# 4. MIDDLEWARE
# ==============================================================================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',                        # Must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',      # Logs user in
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Custom Middleware
    'audit.middleware.AuditMiddleware',                             # Captures user context for logs
]

ROOT_URLCONF = 'hrms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hrms.wsgi.application'


# ==============================================================================
# 5. DATABASE
# ==============================================================================
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}

# Custom User Model
AUTH_USER_MODEL = env('AUTH_USER_MODEL')


# ==============================================================================
# 6. PASSWORD VALIDATION
# ==============================================================================
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==============================================================================
# 7. INTERNATIONALIZATION
# ==============================================================================
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==============================================================================
# 8. STATIC & MEDIA FILES
# ==============================================================================
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# In production, run 'python manage.py collectstatic' to move files here
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# URL used to access media (e.g., http://localhost:8000/media/face.jpg)
MEDIA_URL = '/media/'

# Path where uploaded files are stored on the disk
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ==============================================================================
# 9. API CONFIGURATION (DRF & JWT)
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),     # Recommended: shorter (e.g., 15 mins) in prod
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'HRMS API',
    'DESCRIPTION': 'Human Resource Management System API with V1/V2 versioning',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# ==============================================================================
# 10. CORS CONFIGURATION
# ==============================================================================

# If True, allows any website to call your API (Development only)
CORS_ALLOW_ALL_ORIGINS = DEBUG

# In production, set CORS_ALLOW_ALL_ORIGINS = False and use the list below
if not DEBUG:
    CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')