# Generated by Django 6.0 on 2026-03-10 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_alter_employeesalarystructure_employee_salary_structure_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycomponent',
            name='is_basic_salary',
            field=models.BooleanField(default=False, help_text='Mark as True for the Basic Salary component. Only one component should have this set.'),
        ),
        migrations.AlterField(
            model_name='employeesalarystructure',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='System-calculated. FIXED: flat value. PERCENTAGE: derived from CTC/Basic.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='default_value',
            field=models.DecimalField(decimal_places=2, help_text='For FIXED: flat monthly amount in INR. For PERCENTAGE: percentage value (e.g., 50 for 50%).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
